version: '3.8'


services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nipun@123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes: 
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

  # .NET API
  api:
    build: ./backend
    container_name: api-container
    ports:
      - "5062:5062"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ERSDB;User Id=sa;Password=Nipun@123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5062
    depends_on:
      - sqlserver
    networks:
      - app-network

  # React Frontend
  client:
    build: ./frontend
    container_name: client-container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - VITE_API_URL=http://localhost:5062
      - VITE_HOST=0.0.0.0
    depends_on:
      - api
    networks:
      - app-network

volumes:
  sqlserver_data:

networks:
  app-network:
    driver: bridge
