version: '3.8'


services:
  #.NET
  api:
    build: ./backend
    container_name: api-container
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app 
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1

#React
  client:
    build: ./frontend
    container_name: client-container
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    stdin_open: true 
    tty: true
    depends_on:
      - api 