apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: ers-backend
data:
  ASPNETCORE_URLS: "http://+:5062"
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_USE_POLLING_FILE_WATCHER: "1"
