apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: ers-db
type: Opaque
stringData:
  SA_PASSWORD: "YourSecurePassword@123"  # Change this to a secure password
  DB_NAME: "ElectronicsRepairShop"
