apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: ers-db
  labels:
    app: sqlserver
spec:
  type: ClusterIP
  selector:
    app: sqlserver
  ports:
  - name: sql-port
    port: 1433
    targetPort: 1433
    protocol: TCP
