apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database/namespace.yaml
  - database/configmap.yaml
  - database/secret.yaml
  - database/pvc.yaml
  - database/deployment.yaml
  - database/service.yaml
  - backend/namespace.yaml
  - backend/configmap.yaml
  - backend/secret.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/namespace.yaml
  - frontend/configmap.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
